apply plugin: 'java-library'
apply plugin: 'maven-publish'
apply plugin: 'application'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    options.release = 11
}

dependencies {
    api project(':satochip-lib')
}

application {
    mainClass = 'org.satochip.desktop.Main'
}

publishing {
    publications {
        maven(MavenPublication) {
            artifactId = 'satochip-desktop'
            from components.java
        }
    }
}
