apply plugin: 'java'
apply plugin: 'maven-publish'
apply plugin: 'application'

dependencies {
    compile project(':satochip-lib')
    //compile 'org.hid4java:hid4java:0.5.0'
}

task sourcesJar(type: Jar, dependsOn: classes) {
    classifier = 'sources'
    from sourceSets.main.allSource
}

task javadocJar(type: Jar, dependsOn: javadoc) {
    classifier = 'javadoc'
    from javadoc.destinationDir
}

artifacts {
    archives sourcesJar
    archives javadocJar
}

publishing {
    publications {
        maven(MavenPublication) {
            artifactId = 'satochip-desktop'
            from components.java
            artifact sourcesJar
        }
    }
}

mainClassName = "org.satochip.desktop.Main"
